// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_loglik_total
double cpp_loglik_total(Rcpp::NumericMatrix A, Rcpp::NumericMatrix D, Rcpp::NumericMatrix y, Rcpp::NumericMatrix r, int model_type, Rcpp::NumericMatrix llik_tab, Rcpp::Nullable<Rcpp::NumericVector> loglik_const, Rcpp::Nullable<Rcpp::IntegerVector> obs_code);
RcppExport SEXP _snp_slicer_cpp_loglik_total(SEXP ASEXP, SEXP DSEXP, SEXP ySEXP, SEXP rSEXP, SEXP model_typeSEXP, SEXP llik_tabSEXP, SEXP loglik_constSEXP, SEXP obs_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type llik_tab(llik_tabSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type loglik_const(loglik_constSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type obs_code(obs_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_loglik_total(A, D, y, r, model_type, llik_tab, loglik_const, obs_code));
    return rcpp_result_gen;
END_RCPP
}
// cpp_build_kernel_obs_cache
Rcpp::List cpp_build_kernel_obs_cache(Rcpp::NumericMatrix y, Rcpp::NumericMatrix r, int model_type);
RcppExport SEXP _snp_slicer_cpp_build_kernel_obs_cache(SEXP ySEXP, SEXP rSEXP, SEXP model_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_build_kernel_obs_cache(y, r, model_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_a
Rcpp::List cpp_update_a(Rcpp::NumericMatrix A, Rcpp::NumericMatrix D, Rcpp::NumericVector mu, Rcpp::IntegerVector mixed, int kplus, int kstar, Rcpp::NumericMatrix y, Rcpp::NumericMatrix r, int model_type, Rcpp::NumericMatrix llik_tab, Rcpp::Nullable<Rcpp::NumericVector> loglik_const, Rcpp::Nullable<Rcpp::IntegerVector> obs_code);
RcppExport SEXP _snp_slicer_cpp_update_a(SEXP ASEXP, SEXP DSEXP, SEXP muSEXP, SEXP mixedSEXP, SEXP kplusSEXP, SEXP kstarSEXP, SEXP ySEXP, SEXP rSEXP, SEXP model_typeSEXP, SEXP llik_tabSEXP, SEXP loglik_constSEXP, SEXP obs_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mixed(mixedSEXP);
    Rcpp::traits::input_parameter< int >::type kplus(kplusSEXP);
    Rcpp::traits::input_parameter< int >::type kstar(kstarSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type llik_tab(llik_tabSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type loglik_const(loglik_constSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type obs_code(obs_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_a(A, D, mu, mixed, kplus, kstar, y, r, model_type, llik_tab, loglik_const, obs_code));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_d
Rcpp::NumericMatrix cpp_update_d(Rcpp::NumericMatrix A, Rcpp::NumericMatrix D, Rcpp::IntegerVector an, int kmin, int kstar, Rcpp::NumericMatrix y, Rcpp::NumericMatrix r, double rho, int model_type, Rcpp::NumericMatrix llik_tab, Rcpp::Nullable<Rcpp::NumericVector> loglik_const, Rcpp::Nullable<Rcpp::IntegerVector> obs_code);
RcppExport SEXP _snp_slicer_cpp_update_d(SEXP ASEXP, SEXP DSEXP, SEXP anSEXP, SEXP kminSEXP, SEXP kstarSEXP, SEXP ySEXP, SEXP rSEXP, SEXP rhoSEXP, SEXP model_typeSEXP, SEXP llik_tabSEXP, SEXP loglik_constSEXP, SEXP obs_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type an(anSEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< int >::type kstar(kstarSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type llik_tab(llik_tabSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type loglik_const(loglik_constSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type obs_code(obs_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_d(A, D, an, kmin, kstar, y, r, rho, model_type, llik_tab, loglik_const, obs_code));
    return rcpp_result_gen;
END_RCPP
}
// cpp_slice_iter
Rcpp::List cpp_slice_iter(Rcpp::NumericMatrix A, Rcpp::NumericMatrix D, Rcpp::NumericVector mu, Rcpp::IntegerVector mixed, int kplus, int kstar, int kmin, int ktrunc, Rcpp::NumericMatrix y, Rcpp::NumericMatrix r, double rho, double alpha, int N, int P, int model_type, Rcpp::NumericMatrix llik_tab, Rcpp::Nullable<Rcpp::NumericVector> loglik_const, Rcpp::Nullable<Rcpp::IntegerVector> obs_code);
RcppExport SEXP _snp_slicer_cpp_slice_iter(SEXP ASEXP, SEXP DSEXP, SEXP muSEXP, SEXP mixedSEXP, SEXP kplusSEXP, SEXP kstarSEXP, SEXP kminSEXP, SEXP ktruncSEXP, SEXP ySEXP, SEXP rSEXP, SEXP rhoSEXP, SEXP alphaSEXP, SEXP NSEXP, SEXP PSEXP, SEXP model_typeSEXP, SEXP llik_tabSEXP, SEXP loglik_constSEXP, SEXP obs_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mixed(mixedSEXP);
    Rcpp::traits::input_parameter< int >::type kplus(kplusSEXP);
    Rcpp::traits::input_parameter< int >::type kstar(kstarSEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< int >::type ktrunc(ktruncSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type llik_tab(llik_tabSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type loglik_const(loglik_constSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type obs_code(obs_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_slice_iter(A, D, mu, mixed, kplus, kstar, kmin, ktrunc, y, r, rho, alpha, N, P, model_type, llik_tab, loglik_const, obs_code));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_s
Rcpp::List cpp_update_s(Rcpp::NumericMatrix A, Rcpp::NumericMatrix D, Rcpp::NumericVector mu, int ktrunc, double alpha, double rho, int P);
RcppExport SEXP _snp_slicer_cpp_update_s(SEXP ASEXP, SEXP DSEXP, SEXP muSEXP, SEXP ktruncSEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type ktrunc(ktruncSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_s(A, D, mu, ktrunc, alpha, rho, P));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_mu
Rcpp::NumericVector cpp_update_mu(Rcpp::NumericMatrix A, Rcpp::NumericVector mu, int kplus, int ktrunc, int N, double alpha);
RcppExport SEXP _snp_slicer_cpp_update_mu(SEXP ASEXP, SEXP muSEXP, SEXP kplusSEXP, SEXP ktruncSEXP, SEXP NSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type kplus(kplusSEXP);
    Rcpp::traits::input_parameter< int >::type ktrunc(ktruncSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_mu(A, mu, kplus, ktrunc, N, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_snp_slicer_cpp_loglik_total", (DL_FUNC) &_snp_slicer_cpp_loglik_total, 8},
    {"_snp_slicer_cpp_build_kernel_obs_cache", (DL_FUNC) &_snp_slicer_cpp_build_kernel_obs_cache, 3},
    {"_snp_slicer_cpp_update_a", (DL_FUNC) &_snp_slicer_cpp_update_a, 12},
    {"_snp_slicer_cpp_update_d", (DL_FUNC) &_snp_slicer_cpp_update_d, 12},
    {"_snp_slicer_cpp_slice_iter", (DL_FUNC) &_snp_slicer_cpp_slice_iter, 18},
    {"_snp_slicer_cpp_update_s", (DL_FUNC) &_snp_slicer_cpp_update_s, 7},
    {"_snp_slicer_cpp_update_mu", (DL_FUNC) &_snp_slicer_cpp_update_mu, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_snp_slicer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
