# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_loglik_total <- function(A, D, y, r, model_type, llik_tab, loglik_const = NULL, obs_code = NULL) {
    .Call(`_snp_slicer_cpp_loglik_total`, A, D, y, r, model_type, llik_tab, loglik_const, obs_code)
}

cpp_build_kernel_obs_cache <- function(y, r, model_type) {
    .Call(`_snp_slicer_cpp_build_kernel_obs_cache`, y, r, model_type)
}

cpp_update_a <- function(A, D, mu, mixed, kplus, kstar, y, r, model_type, llik_tab, loglik_const = NULL, obs_code = NULL) {
    .Call(`_snp_slicer_cpp_update_a`, A, D, mu, mixed, kplus, kstar, y, r, model_type, llik_tab, loglik_const, obs_code)
}

cpp_update_d <- function(A, D, an, kmin, kstar, y, r, rho, model_type, llik_tab, loglik_const = NULL, obs_code = NULL) {
    .Call(`_snp_slicer_cpp_update_d`, A, D, an, kmin, kstar, y, r, rho, model_type, llik_tab, loglik_const, obs_code)
}

cpp_slice_iter <- function(A, D, mu, mixed, kplus, kstar, kmin, ktrunc, y, r, rho, alpha, N, P, model_type, llik_tab, loglik_const = NULL, obs_code = NULL) {
    .Call(`_snp_slicer_cpp_slice_iter`, A, D, mu, mixed, kplus, kstar, kmin, ktrunc, y, r, rho, alpha, N, P, model_type, llik_tab, loglik_const, obs_code)
}

cpp_update_s <- function(A, D, mu, ktrunc, alpha, rho, P) {
    .Call(`_snp_slicer_cpp_update_s`, A, D, mu, ktrunc, alpha, rho, P)
}

cpp_update_mu <- function(A, mu, kplus, ktrunc, N, alpha) {
    .Call(`_snp_slicer_cpp_update_mu`, A, mu, kplus, ktrunc, N, alpha)
}

